### ISSUE TITLE
Add Casbin-CPP and its competitors to trend page

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-cpp#52]
Please find Casbin-CPP's competitors (open-source authz project) and add them to our trend page like other languages: https://trend.casbin.org/

See Go as an example:

![image](https://user-images.githubusercontent.com/3787410/86028626-b090d880-ba64-11ea-8fae-6d680fb07ee7.png)

**Comment by hsluoyz** [comment]
@xcaptain @divy9881 @zipochan can anyone do this?

**Comment by divy9881** [comment]
Okay, i will do this.

**Comment by divy9881** [comment]
I just found one open-source project for C++ authz, which is also not so interesting, BTW
https://github.com/AlexeyParhomenko/x-acl
The keywords, I used to search are "Docker authz plugin C++", "Access control and role-based authz C++", but I couldn't find more, which is a good thing I think so that we can monopolize our library 😆 😎

**Comment by hsluoyz** [comment]
@divy9881 good. Please make a PR to add it to: https://trend.casbin.org/
